### ISSUE TITLE
Need to remove corrupt file: apps/pokemon-bff/src/assets/type:-null.jpg

### ISSUE THREAD

**Issue by ThePiyushAggarwal** [jherr/portable-react-apps#1]
This file created some problems while I was cloning using GitHub Desktop on Windows.
And when I download the ZIP and extracted on windows, it couldn't extract properly.
Normal `git clone ...`  works but git shows some problem with this file still.
Please remove this file.

**Comment by ThePiyushAggarwal** [comment]
A simple search shows some more places it has been referenced.

![image](https://github.com/jherr/portable-react-apps/assets/27003616/ec6c0724-1a74-4e27-9f66-1af9f547bcb3)

**Comment by jherr** [comment]
Feel free to PR a fix.
